config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  get 'messages/:id' => 'messages#message', as: 'message'
  post 'messages' => 'messages#create', as: 'messages'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      flash.now[:notice] = 'コメントを投稿しました'
    render :comments
    else
    render 'books/show'
    end
  end


  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    flash.now[:alert] = 'コメントを削除しました'
    @book = Book.find(params[:book_id])
    render :comments
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment,)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comments.html.erb
        <% @book.book_comments.each do |book_comment| %>
        <table class='table'>
          <tr>
            <td>
              <%= image_tag book_comment.user.get_profile_image(50,50) %><br>
              <%= link_to user_path(@book) do %>
              <%= book_comment.user.name %>
              <% end %>
              </td>
            <td>
              <%= book_comment.comment %>
              <% if book_comment.user == current_user %>
            </td>
            <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %></td>
              <% end %>
          </tr>
          <% end %>
        </table>

app/views/book_comments/_form.html.erb
        <%= form_with model:[@book, @book_comment], local: false do |f| %>
          <%= f.text_area :comment, rows: '4', placeholder: "コメントをここに", class: 'form-control',size: "5x5" %>
          <%= f.submit "送信" %>
          <% end %>

app/views/book_comments/comments.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'book_comments/book_comments', book: @book, book_comment: @book_comment) %>");
$('#comment_count').html("<%= @book.book_comments.count %>")
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');